// cli/harness-wrapper.test.ts — pass-6 finding F-T3.
//
// Pass 5 made the Codex overlay secret guard "no longer silent" when it cannot find the canonical
// core. Pass 6 found that fix reached exactly one of six agents: the wrappers GENERATED by
// harness/core/install.sh for Claude, Gemini, Cursor, OpenCode and generic still failed open with
// exit 0 and an empty stderr. Claude Code — the orchestrator in the author's own workflow — got the
// silent version. A disabled secret guard that says nothing is indistinguishable from one that ran
// and allowed the call.
//
// This runs the REAL installer, then exercises the REAL generated artifact — not a paraphrase of the
// template — against the missing-core path, because that is the whole lesson of the pass-3 defect.

import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, readFileSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");

function have(bin: string): boolean {
  return spawnSync(bin, ["--version"], { encoding: "utf8" }).status === 0;
}

const CAN_RUN = have("jq") && have("bun");
const d = CAN_RUN ? describe : describe.skip;

let sandboxHome = "";
let generatedGuard = "";

beforeAll(() => {
  if (!CAN_RUN) return;
  sandboxHome = mkdtempSync(join(tmpdir(), "ebrain-harness-"));
  // Install the "generic" adapter: it needs no external agent binary and generates the same wrapper
  // shape as every other agent, including a guard-secrets.sh wrapper.
  const res = spawnSync("bash", [join(ROOT, "harness", "core", "install.sh"), "generic"], {
    encoding: "utf8",
    env: { ...process.env, HOME: sandboxHome, EBRAIN_HOME: ROOT, EBRAIN_CONTRACT_TESTED: "1" },
  });
  // The installer prints its progress; failure here is a real install regression, so surface it.
  if (res.status !== 0) throw new Error(`harness install generic failed: ${res.stderr || res.stdout}`);
  generatedGuard = join(sandboxHome, ".config", "ebrain", "generic-hooks", "guard-secrets.sh");
});

afterAll(() => {
  if (sandboxHome) rmSync(sandboxHome, { recursive: true, force: true });
});

/** Copy the generated guard wrapper with its baked EBRAIN_HOME redirected to a nonexistent path. */
function guardWithBrokenHome(): string {
  const src = readFileSync(generatedGuard, "utf8");
  const broken = src.replaceAll(ROOT, "/tmp/ebrain-gone-home");
  const out = join(sandboxHome, "broken-guard.sh");
  writeFileSync(out, broken, { mode: 0o755 });
  chmodSync(out, 0o755);
  return out;
}

d("F-T3 — the generated secret-guard wrapper is not silent when its core is missing", () => {
  test("the installer actually generated a guard wrapper", () => {
    expect(existsSync(generatedGuard)).toBe(true);
  });

  test("the generated artifact carries the non-silent path (not just the template)", () => {
    const src = readFileSync(generatedGuard, "utf8");
    expect(src).toContain("INACTIVE");
    expect(src).toContain("EBRAIN_GUARD_STRICT");
    expect(src).toContain("guard-secrets.sh");
  });

  test("with the core unreachable, it warns to stderr and stays fail-open (exit 0)", () => {
    const res = spawnSync("bash", [guardWithBrokenHome()], {
      encoding: "utf8",
      input: "{}",
      env: { PATH: process.env.PATH ?? "", HOME: sandboxHome },
    });
    expect(res.status).toBe(0);
    expect(res.stderr).toContain("INACTIVE");
  });

  test("EBRAIN_GUARD_STRICT=1 turns the missing secret guard into a denial (exit 2)", () => {
    const res = spawnSync("bash", [guardWithBrokenHome()], {
      encoding: "utf8",
      input: "{}",
      env: { PATH: process.env.PATH ?? "", HOME: sandboxHome, EBRAIN_GUARD_STRICT: "1" },
    });
    expect(res.status).toBe(2);
  });

  test("a non-security wrapper (inject-context) stays fail-open even under strict mode", () => {
    // Blocking a session start because a context hook moved would be worse than the gap it covers;
    // only the secret guard escalates under strict mode.
    const ctx = join(sandboxHome, ".config", "ebrain", "generic-hooks", "inject-context.sh");
    const src = readFileSync(ctx, "utf8").replaceAll(ROOT, "/tmp/ebrain-gone-home");
    const out = join(sandboxHome, "broken-ctx.sh");
    writeFileSync(out, src, { mode: 0o755 });
    chmodSync(out, 0o755);
    const res = spawnSync("bash", [out], {
      encoding: "utf8",
      input: "{}",
      env: { PATH: process.env.PATH ?? "", HOME: sandboxHome, EBRAIN_GUARD_STRICT: "1" },
    });
    expect(res.status).toBe(0);
  });
});
