/**
 * tui/src/commands.ts — SINGLE source of truth for keybinds (SPRINT-TUI 6.3.3).
 *
 * `COMMANDS` feeds the hint bar TODAY, and (next chunk, 6.3.4/6.3.5) the command
 * palette (`/`, `ctrl+p`) and the autogenerated help overlay (`?`) — same registry,
 * three consumers, never hand-copied strings. This is the claude-code rule: hints /
 * help / keybinds can never drift from what the app actually does because they are
 * all views over this one array.
 *
 * `run` is intentionally loose (`(app: unknown) => void`) — this chunk resolves
 * navigation through the pure `reduce()` in app.ts (testable without a command
 * dispatcher), not through `Command.run`. `run` becomes load-bearing once the
 * palette (6.3.4) needs to actually EXECUTE a selected command; wiring it now would
 * be dead code with no caller. Until then it stays `undefined` for every entry.
 */

/** The 6 top-level views, in tab order (1-based key = index+1). Mirrors the
 * mockup's `TABS` in design-system/ui_kits/ebrain/shell.jsx exactly. */
export type TabName = "home" | "sessions" | "launch" | "memory" | "routing" | "doctor";

export const TABS: readonly TabName[] = ["home", "sessions", "launch", "memory", "routing", "doctor"];

export interface Command {
  id: string;
  title: string;
  summary: string;
  /** The literal key that triggers it (e.g. "1", "tab", "shift+tab", "ctrl+l"). */
  key?: string;
  /** Display-only override for the hint bar when `key` isn't the compact form
   * shown to the user (e.g. six per-tab jump commands collapse to one "1-6" hint). */
  hintKey?: string;
  group?: "nav" | "global";
  /** Whether this command's key/title pair appears in the bottom hint bar.
   * Kept separate from `group` so a command can exist for help-overlay /
   * palette purposes (6.3.4/6.3.5) without cluttering the always-visible bar. */
  showInHintBar?: boolean;
  run?: (app: unknown) => void;
}

export const COMMANDS: Command[] = [
  // ── per-tab direct-jump (1..6) — individually addressable for the future
  // help overlay (6.3.5), collapsed to one "1-6" entry below for the hint bar.
  { id: "nav.home", title: "home", summary: "ir a la vista home", key: "1", group: "nav" },
  { id: "nav.sessions", title: "sessions", summary: "ir a la vista sessions", key: "2", group: "nav" },
  { id: "nav.launch", title: "launch", summary: "ir a la vista launch", key: "3", group: "nav" },
  { id: "nav.memory", title: "memory", summary: "ir a la vista memory", key: "4", group: "nav" },
  { id: "nav.routing", title: "routing", summary: "ir a la vista routing", key: "5", group: "nav" },
  { id: "nav.doctor", title: "doctor", summary: "ir a la vista doctor", key: "6", group: "nav" },

  // ── compact hint-bar entry for the six jumps above (matches HomeScreen's
  // {k:'1-6', label:'vistas'} in screens-a.jsx) — not itself a dispatchable key.
  {
    id: "nav.tabs",
    title: "vistas",
    summary: "saltar a una vista por numero (1-6), o ciclar con tab / shift+tab",
    key: "1-6",
    group: "nav",
    showInHintBar: true,
  },

  { id: "nav.cycleNext", title: "siguiente vista", summary: "ciclar a la siguiente pestana", key: "tab", group: "nav" },
  { id: "nav.cyclePrev", title: "vista anterior", summary: "ciclar a la pestana anterior", key: "shift+tab", group: "nav" },

  // ── global — stub targets for the next chunk (6.3.4 palette / 6.3.5 help).
  { id: "palette.open", title: "palette", summary: "abrir la paleta de comandos (proximamente)", key: "/", group: "global", showInHintBar: true },
  { id: "app.help", title: "ayuda", summary: "mostrar la ayuda autogenerada del registry (proximamente)", key: "?", group: "global", showInHintBar: true },
  { id: "nav.launchShortcut", title: "launch", summary: "atajo directo a la vista launch", key: "l", group: "global", showInHintBar: true },
  { id: "app.quit", title: "salir", summary: "salir de ebrain ui (q, ctrl+c dos veces, o ctrl+d)", key: "q", group: "global" },
  { id: "app.redraw", title: "redraw", summary: "forzar redibujado completo de la pantalla", key: "ctrl+l", group: "global" },
];

/** A single hint-bar entry: `{k, label}` per widgets/chrome/hintbar.ts's contract. */
export interface HintEntry {
  k: string;
  label: string;
  disabled?: boolean;
}

/**
 * The hints shown in the bottom hint bar for the given tab.
 *
 * All 6 tabs currently show the SAME global set (nav + palette + help + launch
 * shortcut): only `home` is a real view this chunk (6.3.3) — the other 5 are stub
 * "proximamente" panels with no per-view actions to hint at yet. Per-view hints
 * (like SessionsScreen's `a attach / k kill / p prompt` in screens-a.jsx) land once
 * those views are actually built (F6.4+). Keeping the signature `(tab) => HintEntry[]`
 * now avoids a breaking change to the hint bar's call site later.
 */
export function hintsForTab(_tab: TabName): HintEntry[] {
  return COMMANDS.filter((c) => c.showInHintBar).map((c) => ({
    k: c.hintKey ?? c.key ?? "",
    label: c.title,
  }));
}
