/**
 * tui/src/commands.ts — SINGLE source of truth for keybinds (SPRINT-TUI 6.3.3).
 *
 * `COMMANDS` feeds the hint bar TODAY, and (next chunk, 6.3.4/6.3.5) the command
 * palette (`/`, `ctrl+p`) and the autogenerated help overlay (`?`) — same registry,
 * three consumers, never hand-copied strings. This is the claude-code rule: hints /
 * help / keybinds can never drift from what the app actually does because they are
 * all views over this one array.
 *
 * `run` is intentionally loose (`(app: unknown) => void`) — this chunk resolves
 * navigation through the pure `reduce()` in app.ts (testable without a command
 * dispatcher), not through `Command.run`. `run` becomes load-bearing once the
 * palette (6.3.4) needs to actually EXECUTE a selected command; wiring it now would
 * be dead code with no caller. Until then it stays `undefined` for every entry.
 */

/** The 7 top-level views, in tab order (1-based key = index+1). Mirrors the
 * mockup's `TABS` in design-system/ui_kits/ebrain/shell.jsx exactly. */
export type TabName = "home" | "sessions" | "launch" | "workspaces" | "memory" | "routing" | "doctor";

export const TABS: readonly TabName[] = ["home", "launch", "sessions", "workspaces", "memory", "routing", "doctor"];

export interface Command {
  id: string;
  title: string;
  summary: string;
  /** The literal key that triggers it (e.g. "1", "tab", "shift+tab", "ctrl+l"). */
  key?: string;
  /** Display-only override for the hint bar when `key` isn't the compact form
   * shown to the user (e.g. seven per-tab jump commands collapse to one "1-7" hint). */
  hintKey?: string;
  group?: "nav" | "global";
  /** Whether this command's key/title pair appears in the bottom hint bar.
   * Kept separate from `group` so a command can exist for help-overlay /
   * palette purposes (6.3.4/6.3.5) without cluttering the always-visible bar. */
  showInHintBar?: boolean;
  run?: (app: unknown) => void;
}

export const COMMANDS: Command[] = [
  // ── per-tab direct-jump (1..7) — individually addressable for the future
  // help overlay (6.3.5), collapsed to one "1-7" entry below for the hint bar.
  { id: "nav.home", title: "home", summary: "go to the home view", key: "1", group: "nav" },
  { id: "nav.launch", title: "launch", summary: "go to the launch view", key: "2", group: "nav" },
  { id: "nav.sessions", title: "sessions", summary: "go to the sessions view", key: "3", group: "nav" },
  { id: "nav.workspaces", title: "workspaces", summary: "organize validated project directories", key: "4", group: "nav" },
  { id: "nav.memory", title: "memory", summary: "go to the memory view", key: "5", group: "nav" },
  { id: "nav.routing", title: "routing", summary: "go to the routing view", key: "6", group: "nav" },
  { id: "nav.doctor", title: "doctor", summary: "go to the doctor view", key: "7", group: "nav" },

  // ── compact hint-bar entry for the six jumps above (matches HomeScreen's
  // {k:'1-7', label:'views'} in screens-a.jsx) — not itself a dispatchable key.
  {
    id: "nav.tabs",
    title: "views",
    summary: "jump to a view by number (1-7), or cycle with tab / shift+tab",
    key: "1-7",
    group: "nav",
    showInHintBar: true,
  },

  { id: "focus.next", title: "focus next box", summary: "move the focus ring to the next box in this view", key: "tab", group: "nav" },
  { id: "focus.prev", title: "focus previous box", summary: "move the focus ring to the previous box in this view", key: "shift+tab", group: "nav" },
  { id: "focus.drill", title: "open / attach", summary: "act on the focused box (attach a session, open a memory, …)", key: "enter", group: "nav" },

  // ── global. Order matches screens-a.jsx HomeScreen hints exactly: 1-7 views ·
  // / palette · l launch · ? help — hintsForTab() preserves COMMANDS array order below.
  { id: "palette.open", title: "palette", summary: "open the command palette", key: "/", group: "global", showInHintBar: true },
  { id: "nav.launchShortcut", title: "launch", summary: "jump straight to the launch view", key: "l", group: "global", showInHintBar: true },
  { id: "app.help", title: "help", summary: "show the auto-generated help from the registry", key: "?", group: "global", showInHintBar: true },
  { id: "app.quit", title: "exit", summary: "exit ebrain ui (q, ctrl+c twice, or ctrl+d)", key: "q", group: "global" },
  { id: "app.redraw", title: "redraw", summary: "force a full screen redraw", key: "ctrl+l", group: "global" },
];

/** A single hint-bar entry: `{k, label}` per widgets/chrome/hintbar.ts's contract. */
export interface HintEntry {
  k: string;
  label: string;
  disabled?: boolean;
}

/** Per-view hints for the Sessions panel (F6.4.3) — EXACTLY the mockup's
 * SessionsScreen hints in design-system/ui_kits/ebrain/screens-a.jsx line 57
 * (`↑↓ navegar · a attach · k kill · p prompt`). This module is their single source
 * of truth, so the hint bar can never drift from the keys reduce() actually handles. */
const SESSION_HINTS: HintEntry[] = [
  { k: "↑↓", label: "navigate" },
  { k: "enter/a", label: "attach" },
  { k: "k", label: "kill" },
  { k: "p", label: "prompt" },
  // `a`/enter hand the terminal fully to tmux; this is the tmux detach binding that
  // returns you to ebrain (discoverability — see doAttach's on-handoff hint).
  { k: "ctrl+b d", label: "detach" },
];

/** Home is multi-box: Tab moves focus between active-sessions / memories / system. `l` is
 * the launch shortcut the empty sessions box teaches, so the bar advertises the same key
 * instead of leaving the box and the footer pointing at two different routes. Six entries
 * is the bar's ceiling, and this set measures 77 columns at the 80-column minimum. */
const HOME_HINTS: HintEntry[] = [
  { k: "1-7", label: "views" },
  { k: "tab", label: "focus box" },
  { k: "↑↓", label: "select" },
  { k: "enter", label: "open" },
  { k: "l", label: "launch" },
  { k: "?", label: "help" },
];

/** Per-view fallback hints for the Launch panel. The app refines these by focused
 * panel so the footer never pretends one key has two simultaneous meanings. */
const LAUNCH_HINTS: HintEntry[] = [
  { k: "t", label: "task" },
  { k: "w", label: "guided launch" },
  { k: "tab", label: "focus box" },
  { k: "?", label: "actions" },
];
const WORKSPACE_HINTS: HintEntry[] = [
  { k: "↑↓", label: "select" },
  { k: "enter", label: "use in launch" },
  { k: "a", label: "add" },
  { k: "e", label: "rename" },
  { k: "x", label: "remove" },
  { k: "?", label: "actions" },
];

/** Per-view hints for the F6.5 knowledge panels — each matches the keys reduce()
 * actually handles for that tab (screens-b.jsx MemoryScreen / DoctorScreen). */
const MEMORY_HINTS: HintEntry[] = [
  { k: "s", label: "search" },
  { k: "tab", label: "focus box" },
  { k: "↑↓", label: "navigate" },
  { k: "enter", label: "open/run" },
  { k: "a", label: "attach procedure" },
  { k: "r", label: "remember" },
];
const ROUTING_HINTS: HintEntry[] = [
  { k: "↑↓", label: "navigate" },
  { k: "c", label: "cost ledger" },
];
const DOCTOR_HINTS: HintEntry[] = [
  { k: "r", label: "re-run" },
  { k: "tab", label: "focus box" },
  { k: "↑↓", label: "navigate" },
];

/**
 * The hints shown in the bottom hint bar for the given tab.
 *
 * `sessions` shows its own view-scoped actions (the mockup's ↑↓/a/k/p, F6.4.3). The
 * other 5 tabs show the SAME global set (nav + palette + help + launch shortcut):
 * `home` is a real view and the rest are stubs until their views land (F6.5). Per-view
 * hints for those arrive with their views. Keeping `(tab) => HintEntry[]` avoids a
 * breaking change to the hint bar call site.
 */
export function hintsForTab(tab: TabName): HintEntry[] {
  if (tab === "home") return HOME_HINTS;
  if (tab === "sessions") return SESSION_HINTS;
  if (tab === "launch") return LAUNCH_HINTS;
  if (tab === "workspaces") return WORKSPACE_HINTS;
  if (tab === "memory") return MEMORY_HINTS;
  if (tab === "routing") return ROUTING_HINTS;
  if (tab === "doctor") return DOCTOR_HINTS;
  return COMMANDS.filter((c) => c.showInHintBar).map((c) => ({
    k: c.hintKey ?? c.key ?? "",
    label: c.title,
  }));
}
