/**
 * tui/src/help.ts — help overlay, AUTOGENERATED from the command registry
 * (SPRINT-TUI 6.3.5). Renders a centered dialog panel listing every `Command` in
 * COMMANDS grouped by `group`, each as `key  title  — summary`. Because it is
 * generated from the SAME registry that drives the keybinds, the hint bar, and the
 * palette, it can NEVER drift from what the app actually does (the claude-code rule).
 *
 * Pure `(theme[, commands, width]) -> string[]` (the dialog box rows). app.ts
 * centers + composites it over the frame. All color via theme (zero hardcoded hex).
 */
import type { Theme } from "./theme.js";
import { padTo, truncate } from "./kit/draw.js";
import { COMMANDS, type Command } from "./commands.js";
import { panel } from "./widgets/layout/panel.js";

const BOLD = "\x1b[1m";

const GROUP_LABEL: Record<string, string> = { nav: "navigation", global: "global" };
const GROUP_ORDER = ["nav", "global"] as const;

/** Render the help dialog as box rows (square corners — it is a modal). */
export function renderHelp(theme: Theme, commands: Command[] = COMMANDS, width = 66): string[] {
  const keyW = 10;
  const body: string[] = [];

  for (const grp of GROUP_ORDER) {
    const cmds = commands.filter((c) => (c.group ?? "global") === grp);
    if (cmds.length === 0) continue;
    if (body.length > 0) body.push("");
    body.push(theme.fg("text.muted") + (GROUP_LABEL[grp] ?? grp) + theme.reset);
    for (const c of cmds) {
      const kcol = theme.fg("accent.teal") + BOLD + padTo(c.key ?? "", keyW) + theme.reset;
      const title = theme.fg("text.primary") + padTo(truncate(c.title, 13), 14) + theme.reset;
      const summary = theme.fg("text.secondary") + c.summary + theme.reset;
      body.push(kcol + title + summary);
    }
  }

  body.push("");
  body.push(theme.fg("text.muted") + "esc close" + theme.reset);

  const height = body.length + 2;
  // contour-only modal: a teal (focus) dialog border delineates it clearly against the
  // native terminal bg — no interior fill.
  return panel({ title: "help · keybindings", dialog: true, focus: true, width, height, body }, theme);
}
