/**
 * tui/src/help.ts — help overlay, AUTOGENERATED from the command registry
 * (SPRINT-TUI 6.3.5). Renders a centered dialog panel listing every `Command` in
 * COMMANDS grouped by `group`, each as `key  title  — summary`. Because it is
 * generated from the SAME registry that drives the keybinds, the hint bar, and the
 * palette, it can NEVER drift from what the app actually does (the claude-code rule).
 *
 * Pure `(theme[, commands, width]) -> string[]` (the dialog box rows). app.ts
 * centers + composites it over the frame. All color via theme (zero hardcoded hex).
 */
import type { Theme } from "./theme.js";
import { displayWidth } from "./kit/draw.js";
import { COMMANDS, type Command } from "./commands.js";
import { responsiveDialog, type DialogBlock, type ResponsiveDialogResult } from "./widgets/dialog/responsive.js";

const GROUP_LABEL: Record<string, string> = { nav: "navigation", global: "global" };
const GROUP_ORDER = ["nav", "global"] as const;

export interface HelpAction {
  key: string;
  title: string;
  summary: string;
}

/** A compact, view-specific action reference. It is intentionally separate from
 * COMMANDS: these actions can depend on the focused panel and do not belong in the
 * global command palette. */
export interface HelpContext {
  title: string;
  actions: HelpAction[];
}

/** Semantic responsive variant used by app overlays. The legacy `renderHelp()` wrapper remains
 * below for widget tests and consumers that only need rows. */
export function renderHelpLayout(
  theme: Theme,
  commands: Command[] = COMMANDS,
  width = 66,
  context?: HelpContext,
  maxHeight?: number,
  scroll?: number,
): ResponsiveDialogResult {
  const body: DialogBlock[] = [];

  if (context) {
    const keyWidth = Math.max(0, ...context.actions.map((action) => displayWidth(action.key)));
    body.push({ kind: "paragraph", text: context.title, tone: "text.muted" });
    for (const action of context.actions) {
      body.push({ kind: "keyValue", key: action.key, value: action.title, detail: action.summary || undefined, keyTone: "accent.teal", valueTone: "text.primary", keyWidth });
    }
    body.push({ kind: "spacer" });
    body.push({ kind: "line", text: "/ command palette · esc close", tone: "text.muted" });
    return responsiveDialog({ title: "actions", focus: true, width, maxHeight, scroll, blocks: body }, theme);
  }

  const keyWidth = Math.max(0, ...commands.map((c) => displayWidth(c.key ?? "")));
  for (const grp of GROUP_ORDER) {
    const cmds = commands.filter((c) => (c.group ?? "global") === grp);
    if (cmds.length === 0) continue;
    if (body.length > 0) body.push({ kind: "spacer" });
    body.push({ kind: "line", text: GROUP_LABEL[grp] ?? grp, tone: "text.muted" });
    for (const c of cmds) {
      body.push({ kind: "keyValue", key: c.key ?? "", value: c.title, detail: c.summary, keyTone: "accent.teal", valueTone: "text.primary", keyWidth });
    }
  }

  body.push({ kind: "spacer" });
  body.push({ kind: "line", text: "esc close", tone: "text.muted" });

  return responsiveDialog({ title: "help · keybindings", focus: true, width, maxHeight, scroll, blocks: body }, theme);
}

/** Render the help dialog as box rows (square corners -- it is a modal). */
export function renderHelp(theme: Theme, commands: Command[] = COMMANDS, width = 66, context?: HelpContext): string[] {
  return renderHelpLayout(theme, commands, width, context).rows;
}
