import { describe, it, expect } from "bun:test";
import { makeTheme } from "../src/theme.js";
import { parseKey } from "../src/kit/input.js";
import { displayWidth } from "../src/kit/draw.js";
import { COMMANDS } from "../src/commands.js";
import { renderHelp } from "../src/help.js";
import { buildFrame, initialState, reduce } from "../src/app.js";

const t = makeTheme({ trueColor: true, ascii: false });
const strip = (s: string) => s.replace(/\x1b\[[0-9;?]*[A-Za-z]/g, "");

describe("help overlay (autogenerated from COMMANDS)", () => {
  it("renders a square-cornered dialog of exact width", () => {
    const rows = renderHelp(t, COMMANDS, 66);
    for (const r of rows) expect(displayWidth(r)).toBe(66);
    expect(strip(rows[0]!)).toContain("┌"); // dialog = square corners
    expect(strip(rows[0]!)).toContain("help");
  });

  it("contains EVERY keybind registered in COMMANDS (no drift possible)", () => {
    const text = renderHelp(t, COMMANDS, 66).map(strip).join("\n");
    for (const c of COMMANDS) {
      if (!c.key) continue;
      expect(text).toContain(c.key);
    }
  });

  it("groups commands under navigation / global headers", () => {
    const text = renderHelp(t, COMMANDS, 66).map(strip).join("\n");
    expect(text).toContain("navigation");
    expect(text).toContain("global");
  });
});

describe("action-reference app integration (reduce + buildFrame)", () => {
  const size = { cols: 120, rows: 32 };

  it("'?' opens a view-specific action reference; buildFrame composites it", () => {
    const r = reduce(initialState(), parseKey("?"));
    expect(r.state.overlay?.kind).toBe("help");
    const frame = buildFrame(r.state, size, t).map(strip).join("\n");
    expect(frame).toContain("actions");
    expect(frame).toContain("home actions");
    expect(frame).toContain("command palette · esc close");
  });

  it("launch actions explain the three focused decisions without claiming a best model", () => {
    const launch = reduce(initialState(), parseKey("l")).state;
    const opened = reduce(launch, parseKey("?"));
    const frame = buildFrame(opened.state, size, t).map(strip).join("\n");
    expect(frame).toContain("launch actions");
    expect(frame).toContain("guided launch");
    expect(frame).toContain("non-binding task signals");
    expect(frame).not.toContain("best model");
  });

  it("esc closes it", () => {
    const opened = reduce(initialState(), parseKey("?")).state;
    const closed = reduce(opened, parseKey("\x1b"));
    expect(closed.state.overlay).toBeNull();
  });

  it("a key inside help does not quit the app (q dismisses help, not the process)", () => {
    const opened = reduce(initialState(), parseKey("?")).state;
    const afterQ = reduce(opened, parseKey("q"));
    expect(afterQ.quit).toBe(false);
    expect(afterQ.state.overlay).toBeNull();
  });

  it("keeps a long read-only dialog inside 80x24 and lets arrows reveal its remaining text", () => {
    const state = {
      ...initialState(),
      overlay: {
        kind: "detail" as const,
        title: "long detail",
        body: "This detail is intentionally long so a compact terminal must expose a scroll viewport instead of silently dropping the later explanation. ".repeat(12),
      },
    };
    const compact = { cols: 80, rows: 24 };
    const first = buildFrame(state, compact, t);
    expect(first.map(strip).join("\n")).toContain("[↑↓] scroll");
    for (const row of first) expect(displayWidth(row)).toBe(compact.cols);

    const moved = reduce(state, { name: "down" });
    expect(moved.state.overlay).toMatchObject({ kind: "detail", scroll: 1 });
    expect(buildFrame(moved.state, compact, t).map(strip).join("\n")).not.toBe(first.map(strip).join("\n"));
  });
});
