import { describe, it, expect } from "bun:test";
import { makeTheme } from "../src/theme.js";
import { parseKey } from "../src/kit/input.js";
import { displayWidth } from "../src/kit/draw.js";
import { COMMANDS } from "../src/commands.js";
import { renderHelp } from "../src/help.js";
import { buildFrame, initialState, reduce } from "../src/app.js";

const t = makeTheme({ trueColor: true, ascii: false });
const strip = (s: string) => s.replace(/\x1b\[[0-9;?]*[A-Za-z]/g, "");

describe("help overlay (autogenerated from COMMANDS)", () => {
  it("renders a square-cornered dialog of exact width", () => {
    const rows = renderHelp(t, COMMANDS, 66);
    for (const r of rows) expect(displayWidth(r)).toBe(66);
    expect(strip(rows[0]!)).toContain("┌"); // dialog = square corners
    expect(strip(rows[0]!)).toContain("help");
  });

  it("contains EVERY keybind registered in COMMANDS (no drift possible)", () => {
    const text = renderHelp(t, COMMANDS, 66).map(strip).join("\n");
    for (const c of COMMANDS) {
      if (!c.key) continue;
      expect(text).toContain(c.key);
    }
  });

  it("groups commands under navigation / global headers", () => {
    const text = renderHelp(t, COMMANDS, 66).map(strip).join("\n");
    expect(text).toContain("navigation");
    expect(text).toContain("global");
  });
});

describe("help app integration (reduce + buildFrame)", () => {
  const size = { cols: 120, rows: 32 };

  it("'?' opens the help overlay; buildFrame composites it", () => {
    const r = reduce(initialState(), parseKey("?"));
    expect(r.state.overlay?.kind).toBe("help");
    const frame = buildFrame(r.state, size, t).map(strip).join("\n");
    expect(frame).toContain("help · keybindings");
    expect(frame).toContain("esc close");
  });

  it("esc closes it", () => {
    const opened = reduce(initialState(), parseKey("?")).state;
    const closed = reduce(opened, parseKey("\x1b"));
    expect(closed.state.overlay).toBeNull();
  });

  it("a key inside help does not quit the app (q dismisses help, not the process)", () => {
    const opened = reduce(initialState(), parseKey("?")).state;
    const afterQ = reduce(opened, parseKey("q"));
    expect(afterQ.quit).toBe(false);
    expect(afterQ.state.overlay).toBeNull();
  });
});
